### ISSUE TITLE
 CNN network

### ISSUE THREAD

**Issue by yeLer** [griffbr/ODMS#1]
There is no CNN network as discribed in eccv20 paper.

**Comment by griffbr** [comment]
Hello yeLer,

Thanks for your comment! The CNN network from the paper is not provided here. Instead, I wanted to keep this open for researchers to train and test their own network architectures at line 22 in ODMS/demo/demo_datagen.py. With that said, I'm happy to share the PyTorch model code from the eccv20 paper if you send me an email.

Best,
Brent

**Comment by yeLer** [comment]
Hello griffbr,
Thank you for your reply! I get it.

Best regards.

**Comment by griffbr** [comment]
Just as a quick update on this, I have now added a demonstration for training and evaluating various configurations of the ODN method from the paper. See new details in the readme (included below) and new demo scripts [here](https://github.com/griffbr/ODMS/tree/master/demo).

Using ODN Method

Run ./demo/demo_odn_train.py to train your own ODN model using ODMS. 
Run ./demo/demo_odn_eval.py after training to evaluate your ODN model. 
Example training and ODN model configurations are provided in the ./config/ folder. Models are saved in the ./results/model/ folder. 
[native Python, has Torch dependency]
