### ISSUE TITLE
hey bother

### ISSUE THREAD

**Issue by jianling233** [griffbr/ODMS#2]
How can i use this project？

**Comment by griffbr** [comment]
Hi jianling223,

You can use this project any time you need the 3D location of segmented objects from a moving camera. ODMS provides example applications of this in the robotics and driving domain, with more details in our [paper](https://arxiv.org/abs/2007.05676). In more recent [work](https://github.com/griffbr/ODMD), we show that you can even use this type of approach for camera phone images (as long as you can approximate displacements between images).

Best,
Brent
