### ISSUE TITLE
Can I apply the learning model I created to a video?

### ISSUE THREAD

**Issue by kk0320** [griffbr/ODMS#4]
[Nice to meet you. 
I saw the ODMS & ODMD treatises and demos.

I trained and created a learning model with a .pt extension (I just tried the demo code)
I'd like to apply a "made model" to a video like yolo or SSD to see the distance. 
Are you using a different code?

I want to output the result with "target distance from the camera" written like the attached demo image.
I look forward to working with you.

PS: I'm sorry for my poor English. Forgive me.　:'D]
![example_ODMD_phone_results](https://user-images.githubusercontent.com/50560938/112350158-a0184080-8d0c-11eb-820c-374a1409f7f9.jpg)

**Comment by griffbr** [comment]
Hello nomuai,

Thanks for your question! Whether you are working with a video or images, you will need to provide a sequence of segmentation masks (or bounding boxes for ODMD / detection) and camera movement distances. To use video and detection, I would convert the video to a sequence of images (here is a [quick tutorial](https://medium.com/@iKhushPatel/convert-video-to-images-images-to-video-using-opencv-python-db27a128a481) I found for that process) and then process each image using yolo or SSD. Keep in mind, whatever your application, you need to also include an estimate for distance traveled between observations (ODMS or ODMD).

Best,
Brent
