### ISSUE TITLE
Hi, I would like to ask how should I run the code to generate the .pk file after I finish running it through readme.md, and how should I run it next to achieve the detection of images and the display of depth information. What I mean is that I would like to use the camera to implement the demo described in your video. If you can, can you tell me the detailed process of the implementation, thank you and have a safe day.  

### ISSUE THREAD

**Issue by hechengbo-H** [griffbr/ODMS#6]

**Comment by griffbr** [comment]
Hello hechengbo-H,

After reviewing your question, I believe your question is in regards to the Object Depth via Motion and *Detection* Dataset ([https://github.com/griffbr/ODMD](https://github.com/griffbr/ODMD)). If this is correct, do you mind re-posting your question to that repository to avoid confusion?

Thanks!
Brent
